var product_name = "iphone";
var pice =999;
var rating =3.7;
var discount =true;
var size =35;
 console.log(product_name);
 console.log(price);
 console.log(rating);
 console.log(discount);
 console.log(size);